apiVersion: v1
kind: Pod
metadata:
  name: test-pod-4
spec:
  securityContext:
    #runAsNonRoot: true        # <-- K8s check karega ke container root par na chale
    runAsUser: 1009
  containers:
  - name: ubuntu-container-2
    image: ubuntu
    command: [ "sleep", "5000"]
    securityContext:
      runAsUser: 1006
      capabilties:
        add:
        -
  - name: ubuntu-sidecar
    image: ubuntu
    command:
    - "sleep"
    - "4800"
