apiVersion: v1
kind: ConfigMap
metadata:
  name: al-nafi-config
  namespace: default
data:
  APP_PORT: "9090"
  LOG_LEVEL: "info"

  myapp.conf: |
    server {
        listen 9090;
        server_name localhost;
        error_log /var/log/nginx/error.log info;
    }
