apiVersion: v1
kind: Pod
metadata:
  name: al-nafi-pod
  labels:
    app: al-nafi
  namespace: default
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: [ "sleep" ]
    args: [ "10" ]
