apiVersion: batch/v1
kind: Job
metadata:
  name: faulty-report-job
  namespace: default
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
      - name: report-generator
        image: ubuntu
        command: ["/bin/bash", "-c"]
        args:
          - |
            echo "Generating monthly financial report."
            sleep 2
            echo "CRITICAL ERROR: Connection to storage bucket lost!"
            exit 1
      restartPolicy: OnFailure
