apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: al-nafi     # <-- Yeh is kamre (namespace) par apply hoga
spec:
  hard:
    pods: "2"            # Max 2 pods
    requests.cpu: "2"    # Saare pods ka mila kar kam az kam CPU 2 cores
    requests.memory: 2Gi # Saare pods ki mila kar kam az kam RAM 2GB
    limits.cpu: "3"      # Saare pods ki max CPU hadd 3 cores
    limits.memory: 3Gi   # Saare pods ki max RAM hadd 3GB
