apiVersion: v1
kind: Pod
metadata:
  name: al-nafi-pod-3
  namespace: default
  labels:
    name: blue
spec:
   containers:
   - name: internal
     image: kodekloud/webapp-conntest
     env:
     - name: APP_NAME
       value: Blue - Marketinh Application
     - name: BG_COLOR
       value: blue
     ports:
     - containerPort: 8080
       protocol: TCP
