apiVersion: v1
kind: Pod
metadata:
  name: modern-token-pod
  namespace: default
spec:
  serviceAccountName: prometheus-viewer-sa

  containers:
  - name: app-container
    image: ubuntu
    command: ["sleep", "3600"]

    volumeMounts:
    - mountPath: /app/secure-tokens
      name: dynamic-token-volume
  volumes:
  - name: dynamic-token-volume
    projected:
      sources:
      - serviceAccountToken:
          audience: prometheus
          expirationSeconds: 600
          path: token-file
