apiVersion: v1
kind: Pod
metadata:
  name: mix-source-pod
  namespace: default
spec:
  containers:
  - name: my-app-container
    image: ubuntu
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: /app/config-and-tokens
      name: shared-projected-volume
  volumes:
  - name: shared-projected-volume
    projected:
      sources:
      - serviceAccountToken:
          audience: prometheus
          expirationSeconds: 600
          path: token
      - configMap:
          name: my-app-config
          items:
          - key: debug-mode
            path: settings.conf
