apiVersion: v1
kind: Pod
metadata:
  name: secure-app-pod
spec:
  containers:
  - name: app-container
    image: busybox:stable
    command: ["/bin/sh", "-c"]
    args:
    - |
      echo "--- Testing Secret Variable ---"
      echo "Database Password coming from Secret is: $MY_DB_PASS"
      sleep 3600
    env:
    - name: MY_DB_PAS
      valueFrom:
        secretKeyRef:
          name: app-db-secret
          key: DB_PASSWORD
